-- MODELO LOGICO EMPLEADO DEPARTAMENTO CARDINALIDAD 1-N
CREATE DATABASE empleados1n;
USE empleados1n;

CREATE TABLE DPTO
(COD_DPTO VARCHAR(4),
NOMBRE VARCHAR(50));

CREATE TABLE EMPLE
(DNI VARCHAR(9),
NOMBRE VARCHAR(50),
SALARIO FLOAT (8,2),
FECHA_NAC DATE,
COD_DPTO VARCHAR(4));

ALTER TABLE DPTO ADD CONSTRAINT PK_DPTO PRIMARY KEY(COD_DPTO);
ALTER TABLE EMPLE ADD CONSTRAINT PK_EMPLE PRIMARY KEY(DNI);
ALTER TABLE EMPLE ADD CONSTRAINT KF_DPTO_EMPLE_COD_DPTO FOREIGN KEY (COD_DPTO) REFERENCES  DPTO(COD_DPTO);
INSERT INTO DPTO (COD_DPTO,NOMBRE) VALUES ('D001','CONTABILIDAD');
INSERT INTO DPTO (COD_DPTO,NOMBRE) VALUES ('D002','NOMINAS');
INSERT INTO DPTO (COD_DPTO,NOMBRE) VALUES ('D003','FINANZAS');
INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC,COD_DPTO) VALUES ('11111111A','ANA','2000','2000-01-01','D001');
INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC,COD_DPTO) VALUES ('22222222B','KATY','2000','1970-01-01','D002');
INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC,COD_DPTO) VALUES ('33333333C','LAURA','2000','2000-03-03','D003');



