/*empleados n a n */
CREATE DATABASE empleadosnn;
use empleadosnn;
CREATE TABLE DPTO
(ID_DPTO INTEGER(4) AUTO_INCREMENT, 
COD_DPTO VARCHAR(4),
NOMBRE VARCHAR(50),
PRIMARY KEY(ID_DPTO)) ENGINE=InnoDB;
--ALTER TABLE DPTO ADD CONSTRAINT PK_DPTO PRIMARY KEY(ID);
CREATE TABLE EMPLE
(DNI VARCHAR(9),
NOMBRE VARCHAR(50),
SALARIO DOUBLE(8,2),
FECHA_NAC DATE) ENGINE=InnoDB;
ALTER TABLE EMPLE ADD CONSTRAINT PK_EMPLE PRIMARY KEY(DNI);
CREATE TABLE EMPLE_DPTO
(DNI_EMPLE VARCHAR(9),
ID_DPTO INT,
FECHA_INICIO DATE,
FECHA_FIN DATE
)ENGINE=InnoDB;
ALTER TABLE EMPLE_DPTO ADD CONSTRAINT PK_EMPLE_DPTO PRIMARY KEY(ID_DPTO,DNI_EMPLE,FECHA_INICIO);
ALTER TABLE EMPLE_DPTO ADD CONSTRAINT FK_EMPLE_DPTO_DNI FOREIGN KEY (DNI_EMPLE) REFERENCES EMPLE (DNI);
ALTER TABLE EMPLE_DPTO ADD CONSTRAINT FK_EMPLE_DPTO_ID FOREIGN KEY (ID_DPTO) REFERENCES DPTO(ID_DPTO);
DELIMITER $$
CREATE TRIGGER gencoddpto
BEFORE INSERT ON DPTO
FOR EACH ROW
 BEGIN SET NEW.COD_DPTO=CONCAT('D',LPAD((SELECT LAST_INSERT_ID()+1),3,'0'));
END$$
DELIMITER ;
INSERT INTO DPTO (NOMBRE) VALUES ('COMPRAS');
INSERT INTO DPTO (NOMBRE) VALUES ('FINANZAS');
INSERT INTO DPTO (NOMBRE) VALUES ('CONTABILIDAD');
INSERT INTO DPTO (NOMBRE) VALUES ('NOMINAS');
INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC) VALUES ('11111111A','ANA','2000','2000-01-01');
INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC) VALUES ('22222222B','KATY','2000','1970-01-01');
INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC) VALUES ('33333333C','LAURA','2000','2000-03-03');
INSERT INTO EMPLE_DPTO (DNI_EMPLE,ID_DPTO,FECHA_INICIO,FECHA_FIN) VALUES ('11111111A','1','2022-10-03',null);
INSERT INTO EMPLE_DPTO (DNI_EMPLE,ID_DPTO,FECHA_INICIO,FECHA_FIN) VALUES ('22222222B','2','2020-12-20',null);
INSERT INTO EMPLE_DPTO (DNI_EMPLE,ID_DPTO,FECHA_INICIO,FECHA_FIN) VALUES ('33333333C','3','2022-09-24',null);


