create table DPTO
use empleado1n;

create tabl DPTO
(COD_DPTO VARCHAR(4),
NOMBRE VARCHAR(50));

create table EMPLE
(DNI VARCHAR(9),
NOMBRE VARCHAR(50),
SALARIO FLOAT(8,2),
FECHA_NAC DATE,
COD_DPTO VARCHAR (4));

ALTER TABLE DPTO ADD CONSTRAINT PK_DPTO PRIMARY KEY(COD_DPTO);
ALTER TABLE EMPLE ADD CONSTRAINT PK_EMPLE PRIMARY KEY(DNI);
ALTER TABLE EMPLE ADD CONSTRAINT KF_DPTO_EMPLE_COD_DPTO FOREIGN KEY COD_DPTO REFERENCES DPTO (COD_DPTO);